---
title: "county.Rmd"
author: "Henry Sippel"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```


```{r}
load_variables(2018, "acs5") |> 
  filter(concept == "RACE") 
racevars <- c("B02001_002", "B02001_003", "B02001_005", "B03003_003")
             county_data <- get_acs(geography = "tract", 
                       variables = racevars, 
                       year = 2018, 
                       state = "Michigan", 
                       county = "Kent County", 
                       geometry = TRUE, 
                       summary_var = "B02001_001") |> 
              mutate(Percent = (estimate/summary_est)*100) |> 
                ggplot(fill = Percent, color = Percent) +
               facet_wrap(~variable) +
                geom_sf() +
               scale_fill_viridis_c(direction = -1) +
              scale_color_viridis_c(direction = -1) +
               labs(title = "Racial Geography of Kent County, MI", 
                    caption = "Source: American Community Survey 2014-2018") +
               theme_void()
```
