---
title: "deserts.Rmd"
author: "Henry Sippel"
date: '2022-07-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(jsonlite)
library(ggthemes)
```

poorer areas often don’t have access to grocery stores, forcing the people living there to walk for miles just so that they can feed themselves.

```{r}
json_url <- "https://services1.arcgis.com/RLQu0rK7h4kbsBq5/arcgis/rest/services/Store_Locations/FeatureServer/0/query?where=State%20%3D%20'MI'%20AND%20County%20%3D%20'KENT'&outFields=Store_Name,State,County,Longitude,Latitude&outSR=4326&f=json" 
county_stores <- fromJSON(json_url)
county_stores <- county_stores$features$attributes 

county_map <- get_acs(geography = "tract", 
                      variables = "B06012_002", 
                      year = 2018, 
                      state = "Michigan", 
                      county = "Kent County", 
                      geometry = TRUE, 
                      summary_var = "B02001_001") |> 
  mutate(Percent = (estimate/summary_est)*100)


county_map |> 
  ggplot(mapping = aes(fill = Percent, color = Percent)) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  geom_point(data = county_stores, inherit.aes = FALSE,  size = .5, mapping = aes(x = Longitude, y = Latitude)) +
  labs(title = "Grocery Stores and Income in Kent County",
       subtitle = "Grand Rapids is a food desert", 
       caption = "SNAP Retailer Locator, US Department of Agricultural Food and Nutrition Service") +
  theme_void()

```

